// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDUa0p3ABn7gzdapWq8LbeLx7eyMimZpk',
    appId: '1:904790390885:web:704054d21f4b0f14e3ae8c',
    messagingSenderId: '904790390885',
    projectId: 'logi-d686a',
    authDomain: 'logi-d686a.firebaseapp.com',
    storageBucket: 'logi-d686a.firebasestorage.app',
    measurementId: 'G-20WXTDJKY5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgnCQG8jge3pI9CKTFVnGT6JmoSF1refw',
    appId: '1:904790390885:android:2b4cfebad5ac86eae3ae8c',
    messagingSenderId: '904790390885',
    projectId: 'logi-d686a',
    storageBucket: 'logi-d686a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2fJhqfwRUyA9LbrZmfYf75aAS6Wymjt8',
    appId: '1:904790390885:ios:bfc8df5f0370c5abe3ae8c',
    messagingSenderId: '904790390885',
    projectId: 'logi-d686a',
    storageBucket: 'logi-d686a.firebasestorage.app',
    iosClientId: '904790390885-5k7paa46mdovpga75pg42mvtis61nicv.apps.googleusercontent.com',
    iosBundleId: 'com.example.quickdeliver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2fJhqfwRUyA9LbrZmfYf75aAS6Wymjt8',
    appId: '1:904790390885:ios:bfc8df5f0370c5abe3ae8c',
    messagingSenderId: '904790390885',
    projectId: 'logi-d686a',
    storageBucket: 'logi-d686a.firebasestorage.app',
    iosClientId: '904790390885-5k7paa46mdovpga75pg42mvtis61nicv.apps.googleusercontent.com',
    iosBundleId: 'com.example.quickdeliver',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDUa0p3ABn7gzdapWq8LbeLx7eyMimZpk',
    appId: '1:904790390885:web:2e54b5f443afd6f1e3ae8c',
    messagingSenderId: '904790390885',
    projectId: 'logi-d686a',
    authDomain: 'logi-d686a.firebaseapp.com',
    storageBucket: 'logi-d686a.firebasestorage.app',
    measurementId: 'G-6EJ97RXE4E',
  );
}
